version: '3'

services:
  easycachemirror:
    build: .
    container_name: easycachemirror
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      # 持久化数据目录 如果你需要的话取消注释
#      - ./data:/app/data
      - ./data/config.db:/app/data/config.db


volumes:
  data:
    driver: local 